name: Check for Changes

on:
  push:
    branches:
      - package

jobs:
  veracode-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        mvn clean install
    
    - name: package components for analysis
      run: |
        mkdir -p verascan
        cp ./core/target/*.jar ./verascan/
        find ./ -type d -name node_modules -prune -o -type f \( -name "*.html" -o -name "*.js" -o -name "*.jsp" \) -print | zip ./verascan/js-jsp-html.zip -@
   
    - name: debug
      run: |
        ls -la 
        ls -la ./verascan

    - name: upload components for analysis
      uses: veracode/veracode-uploadandscan-action@0.2.6
      with:
        appname: 'AEM'
        createprofile: true
        filepath: './verascan'
        vid: '${{ secrets.API_ID }}'
        vkey: '${{ secrets.API_KEY }}'
